version: '3'
services:
    app-nginx:
        build:
            context: ./docker/development
            dockerfile: nginx.docker
        volumes:
            - ./app:/app:cached
        depends_on:
            - app-php-fpm
        ports:
            - "8080:80"

    app-php-fpm:
        build:
            context: ./docker/development
            dockerfile: php-fpm.docker
        volumes:
            - ./app:/app:cached
        depends_on:
            - app-postgres
            - mailer

    app-php-cli:
        build:
            context: ./docker/development
            dockerfile: php-cli.docker
        volumes:
            - ./app:/app:cached
            - composer:/root/.composer/cache:cached
        depends_on:
            - app-postgres
            - mailer

    app-postgres:
        image: postgres:11.2-alpine
        volumes:
            - app-postgres:/var/lib/postgresql/data:cached
        environment:
            POSTGRES_USER: app
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: app
        ports:
            - "8432:5432"

    app-node:
        image: node:12.7-alpine
        volumes:
            - ./app:/app
        working_dir: /app

    app-node-watch:
        image: node:12.7-alpine
        volumes:
            - ./app:/app:cached
        working_dir: /app
        command: sh -c "until [ -f .ready ] ; do sleep 1 ; done && npm run watch"

    mailer:
        image: mailhog/mailhog
        ports:
            - "8025:8025"

volumes:
    app-postgres:
    composer:
