version: '3'
services:
    nginx:
        build:
            context: ./docker/development
            dockerfile: nginx.docker
        volumes:
            - ./app:/app:cached
        depends_on:
            - php-fpm
        ports:
            - "8080:80"

    php-fpm:
        build:
            context: ./docker/development
            dockerfile: php-fpm.docker
        volumes:
            - ./app:/app:cached
        depends_on:
            - postgres

    php-cli:
        build:
            context: ./docker/development
            dockerfile: php-cli.docker
        volumes:
            - ./app:/app:cached
            - composer:/root/.composer/cache:cached
        depends_on:
            - postgres

    postgres:
        image: postgres:11.2-alpine
        volumes:
            - postgres:/var/lib/postgresql/data:cached
        environment:
            POSTGRES_USER: app
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: app
        ports:
            - "8432:5432"

volumes:
    postgres:
    composer:
