doctrine:
    dbal:
        # configure these for your database server
        # use postgresql for PostgreSQL
        # use sqlite for SQLite
        driver: 'pdo_pgsql'
        server_version: '11.2'

        url: '%env(resolve:DATABASE_URL)%'

        types:
            sport_id: 'App\Model\Entity\Sport\IdType'
            source_id: 'App\Model\Entity\Source\IdType'
            team_id: 'App\Model\Entity\Team\IdType'
            league_id: 'App\Model\Entity\League\IdType'
            game_source_id: 'App\Model\Entity\GameSource\IdType'
            language_id: 'App\Model\Entity\Language\IdType'
            game_id: 'App\Model\Entity\Game\IdType'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Model/Entity'
                prefix: 'App\Model\Entity'
                alias: App
